NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GDHBHJMUPKRXWJTLVL3DM3DUL2JN5HC2J35SJKDBOOYR5OF2LWBENOSW"
]

SIGNING_KEY="GDHBHJMUPKRXWJTLVL3DM3DUL2JN5HC2J35SJKDBOOYR5OF2LWBENOSW"

[[CURRENCIES]]
code="RUGBUNNY"
issuer="GDHBHJMUPKRXWJTLVL3DM3DUL2JN5HC2J35SJKDBOOYR5OF2LWBENOSW"
home_domain="rugbunny.github.io"
status="live"
image="https://rugbunny.github.io/logo.png"
display_decimals=7


conditions="Used for transactions and platform utilities."
image="https://rugbunny.github.io/logo.png"
